name: LiveKit Dev Server
description: |
    Install and run a LiveKit server in development mode for end-to-end testing.
branding:
  icon: server
  color: blue
inputs: {}
outputs: {}
runs:
   using: composite
   steps:
   - name: Install (Linux)
     if: runner.os == 'Linux'
     shell: bash
     run: ${{ github.action_path }}/scripts/install-linux.sh
   - name: Install (macOS)
     if: runner.os == 'macOS'
     shell: bash
     run: ${{ github.action_path }}/scripts/install-macos.sh
   - name: Install (Windows)
     if: runner.os == 'Windows'
     shell: pwsh
     run: ${{ github.action_path }}/scripts/install-windows.ps1
